import { Router } from "express";
import authRoutes from "./authRoutes.js";
import analyticsRoutes from "./analyticsRoutes.js";
import complaintRoutes from "./complaintRoutes.js";
import diningRoutes from "./diningRoutes.js";
import exampleRoutes from "./exampleRoutes.js";
import hallApplicationRoutes from "./hallApplicationRoutes.js";
import imageRecordRoutes from "./imageRecordRoutes.js";
import maintenanceRoutes from "./maintenanceRoutes.js";
import mealRoutes from "./mealRoutes.js";
import noticeRoutes from "./noticeRoutes.js";
import notificationRoutes from "./notificationRoutes.js";
import paymentRoutes from "./paymentRoutes.js";
import roomAllocationRoutes from "./roomAllocationRoutes.js";
import roomRoutes from "./roomRoutes.js";
import staffRoutes from "./staffRoutes.js";
import studentRoutes from "./studentRoutes.js";
import supportTicketRoutes from "./supportTicketRoutes.js";
import systemRoutes from "./systemRoutes.js";
import taskRoutes from "./taskRoutes.js";
import uploadRoutes from "./uploadRoutes.js";
import userRoutes from "./userRoutes.js";
import walletRoutes from "./walletRoutes.js";

const router = Router();

router.use("/", systemRoutes);
router.use("/auth", authRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/complaints", complaintRoutes);
router.use("/maintenance", maintenanceRoutes);
router.use("/notices", noticeRoutes);
router.use("/support-tickets", supportTicketRoutes);
router.use("/tasks", taskRoutes);
router.use("/users", userRoutes);
router.use("/students", studentRoutes);
router.use("/staffs", staffRoutes);
router.use("/hall-applications", hallApplicationRoutes);
router.use("/image-records", imageRecordRoutes);
router.use("/rooms", roomRoutes);
router.use("/room-allocations", roomAllocationRoutes);
router.use("/notifications", notificationRoutes);
router.use("/meals", mealRoutes);
router.use("/wallet", walletRoutes);
router.use("/dining", diningRoutes);
router.use("/payments", paymentRoutes);
router.use("/examples", exampleRoutes);
router.use("/uploads", uploadRoutes);

export default router;
